name: Build documentation
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
        name: Checkout master
        with:
          ref: master
          path: master

    - name: Install doxygen
      run: sudo apt-get install doxygen

    - name: Build documentation
      run: cd 



#     - name: Request Github Pages build job
#       run: >-
#         curl -L -X POST 
#         -H "Content-Type: application/json"
#         -H "Authorization: token ${{ secrets.GITHUB_PAT}}"
#         "https://api.github.com/repos/${{ github.repository }}/pages/builds"
