name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: chombo
      run: install/getChombo.sh
    - name: make
      run: cd execSubcycle; make all
