name: Publish pages
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Request Github Pages build job
      run: >-
        curl -L -X POST 
        -H "Content-Type: application/json"
        -H "Authorization: token ${{ secrets.GITHUB_PAT}}"
        "https://api.github.com/repos/${{ github.repository }}/pages/builds"
        
    # - uses: actions/checkout@v2
    #   name: Checkout master
    #   with:
    #     ref: master
    #     path: master

    # - name: Publish
    #   uses: crazy-max/ghaction-github-pages@v1
    #   with:
    #     target_branch: master
    #     build_dir: .
    #   env:
    #     GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

    # - name: Build and Deploy
    #   uses: JamesIves/github-pages-deploy-action@releases/v3
    #   with:
    #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #     BRANCH: master # The branch the action should deploy to.
    #     FOLDER: . # The folder the action should deploy.