name: RegressionTest

on:
  push:
    branches:
      - 'master'

# schedule:
#   # * is a special character in YAML so you have to quote this string
#   # run at 23:59 every day
#   - cron:  '59 23 * * *'
#   PYTHONPATH: /home/runner/work/mushy-layer/mushy-layer/test:/home/runner/work/mushy-layer/mushy-layer/plotting

env:
  CHOMBO_ROOT: /home/runner/chombo
  CHOMBO_HOME: /home/runner/chombo/lib
  HDF5_PATH: /home/runner/hdf5-dir
  LD_LIBRARY_PATH: /home/runner/hdf5-dir
  PYTHONPATH: /home/runner/work/mushy-layer/mushy-layer/test


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Setup for regressions
        run: |
          cd $GITHUB_WORKSPACE
          python install.py -g

      - name: Run regressions
        run: |
          echo "$PYTHONPATH"
          cd $GITHUB_WORKSPACE/test/regression
          python run_regression_tests.py


#         echo ::set-env name=PYTHONPATH::$(echo $PYTHONPATH):/home/runner/work/mushy-layer/mushy-layer/test:/home/runner/work/mushy-layer/mushy-layer/plotting
# echo "$PYTHONPATH"
#         python install.py -g